language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
script:
  - bash -ex .travis-ocaml.sh
  - eval $(opam config env)
  - make install
  - make lint
  - make test
  - make coverage
  - bisect-ppx-report send-to Coveralls
  - bash -ex ./deploy-docs.sh
env:
  matrix:
    - OCAML_VERSION=4.05
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  fqdn: ocamltest.mukulrathi.com
  on:
    branch: master
  github_token:
    secure: RThYmW+inNaQ7cWah4xjIITe4bvCnFc7SbWtryzQY3fiMWcWfRsN13yyI3YzCSOV2kR3Q15M7IzoS+2DUjv/EZ6H0u3xowaV1q21PowXwgCVDSkwb2/fkc00cGRGpx0zg001yEsBLu42fg3/hPdlQ1IO1Af2EXRPqQHbOWMvwx9kxnayySFtiqKJ7ibU1jNhqouh3GsEjt2w+dz6RFDWWHEApO3e3z/Tt9wneJ2baedv6YPeKLkFFBLFZQmiLvPRJzsvK3f4Sc4Sv8OfHdKi+raedMCGE6d0/I9bJCjNlkV31MeY0prREvDVr8tVPspi0GjDYroBGMGBSZP2tU93LvEhXD8ObUw21lQb8PbXqu8inrxa/rXS1pH2yHInmQ6tEb4Tr5VlF0gyjY8PXYCWsuFO7fjKtqOhPObzuRdS+5Og8u7C4OZxZdhHKzTyhsCS1umJUao0CGEQBNX71W2/hwtnhE12szqJ2MfO0wUUKiPne2bzU8+0r6u3RrqXmG7T0xAVupu5Spuq1vyU/rPv7DXqs8aZQGBYFbXRelvF5Q9sYbfNr138mQORIYzs5q80gk36u6R2v+bLNelRygpGHn1QiUTuDdjhoV8sV6aPKsrLZ2Vs5Fsdsn0r+W/Z88CNbx5VbxZ6jcKq8cXGhyG7M4G0Bxr+t+5XGtjO+KjYY9Q=
before_install:
  - openssl aes-256-cbc -K $encrypted_d61a6e09298b_key -iv $encrypted_d61a6e09298b_iv
    -in .coveralls.yml.enc -out .coveralls.yml -d
