language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
script:
- bash -ex .travis-ocaml.sh
- eval $(opam config env)
- make install
- dune build @fmt
- make test
- make coverage
- bisect-ppx-report send-to Coveralls
- bash -ex ./deploy-docs.sh
env:
  matrix:
  - OCAML_VERSION=4.05
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
  github_token:
    secure: rnX47Ot3Ecqh+kAXzUk0r4UlHNcKOrxYPEfHysVv/wZOF1p3Pzq+qsUsLttB0Tg62UchMU5zs/HUTNURMITHocntLI4lx05V5hlt/H+l5s0Qxn23HTcLOoJGHiFT7fEZviXkuwIHHPkNMQKuvwdbRz8ZniLq02J3PTIN5/6SDlMPlH6yNYNkxySqJE/eVCUXTuARVYX77UdSW73wcSVGgNzZgFW7ZhkVBP67Sq7w35jHDnBz14RWz+6I9TGV+xVdyeeWgtdO2SqEp3CllzElFAlgxpwDKbpGXvQQZQUcaMan5arFFVjwTFpitCFlBM2cvelhjz+zsj9vELSTC5QgB35hBJo589gXhwKHn4DGYaKy3ZYkLJJAR+GdwAaYhs0Je6cED4UUrpgXqjiAjs12L9HzMjgm/hLUVrxgSIgvQC46cQX6u2qQAPW1/81Sije8WL+4QlDbQ8ZJanMworcKkY0IdOjgZBk2YbFCM62o+Xfcy6qtv1nBEZXpUuDA0M/neD2hyQbznmQ+o6yiS0Lr1sx/7OI/r7XBJ7blXAvuMpjk7SXvAjC0yn1ehd/z2w8+VAag71zOHDH+p4L8TDhm1CQ1dHINmgJkAtSF9Oq71dxwf0mIQ/e+vcMtjMsKfK4VYdkR4yUMSrx9bj2gIyP97j8XPUxec3Lap77FqoKHHeE=
before_install:
- openssl aes-256-cbc -K $encrypted_d61a6e09298b_key -iv $encrypted_d61a6e09298b_iv
  -in .coveralls.yml.enc -out .coveralls.yml -d
